[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Antonio Scotti <zengar@gmail.com>"]
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
tinytemplate = "1.2.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
